name: Check membership
description: This action takes your organization name, a user name and organization token, then it returns if the user has a membership for the given organization with check-result parameter
inputs:
  organization-name:
    required: true
  member-name:
    required: true
  token:
    required: true
outputs:
  check-result:
    description: "Membership check result"
    value: ${{ steps.membership-check.outputs.check-result }}
runs:
  steps:
    - id: membership-check
      shell: bash
      run: |-
        response=$(curl -v -H "Authorization: token ${{ inputs.token }}" --write-out '%{http_code}' --silent --output /dev/null "https://api.github.com/orgs/${{ inputs.organization-name }}/memberships/${{ inputs.member-name }}")
        if [[ "$response" -ne 200 ]] ; then
          echo "::set-output name=check-result::false"
        else
          echo "::set-output name=check-result::true"
        fi
